cythral/lambdajection

Directory.Build.props
Add tags to all published NuGet packages.
=> CYTHINF-131 Package Tags

README.md, src/Core/Core.csproj, src/Core/ILambdaStartup.cs, src/Core/LambdaHost.cs, src/Core/packages.lock.json, src/Metapackage/packages.lock.json, tests/GeneratedRunTests.cs, tests/packages.lock.json
Add a default ILogger to the service collection and allow configuring via ILambdaStartup.ConfigureLogging.  This ILogger comes preconfigured to log to the console.
=> CYTHINF-138 Add Logging

.editorconfig, Directory.Build.props, src/Attributes/LambdaAttribute.cs, src/Attributes/packages.lock.json, src/Core/LambdaHost.cs, src/Core/LambdaHostBuilder.cs, src/Core/Properties.cs, src/Core/packages.lock.json, src/Generator/packages.lock.json, src/Metapackage/packages.lock.json, tests/Core/LambdaHostBuilderTests.cs, tests/Core/LambdaHostTests.cs, tests/IntegrationTests.cs, tests/TestLambda.cs, tests/TestStartup.cs, tests/Tests.csproj, tests/packages.lock.json
- Turns on FxCop Analyzers
- Refactored LambdaHost static data initialization into a new internal class, LambdaHostBuilder. 
- Added Unit Tests for LambdaHost and LambdaHostBuilder
- Renamed GeneratedRunTests to IntegrationTests
=> CYTHINF-134 Backfill Tests

.editorconfig, .github/releases/v0.2.1.md, Directory.Build.props, src/Attributes/packages.lock.json, src/Core/LambdaHost.cs, src/Core/LambdaHostBuilder.cs, src/Core/Properties.cs, src/Core/packages.lock.json, src/Generator/LambdaGenerator.cs, src/Generator/packages.lock.json, src/Metapackage/packages.lock.json, tests/Core/LambdaHostBuilderTests.cs, tests/Core/LambdaHostTests.cs, tests/IntegrationTests.cs, tests/TestLambda.cs, tests/TestStartup.cs, tests/Tests.csproj, tests/packages.lock.json, version.json
This release includes unit testing, and introduces the use of roslyn diagnostics to report errors rather than just throwing an exception.
=> CYTHINF-147 v0.2.1

.github/releases/v0.3.0-beta2.md, README.md
Adds NuGet Package Version badges to the README.
=> LAMBJ-7 Package Version Badges

.editorconfig, .github/releases/v0.3.0-beta2.md, build.ps1, src/Attributes/LambdaAttribute.cs, src/Attributes/LambdaOptionsAttribute.cs, src/Core/IAwsFactory.cs, src/Core/ILambda.cs, src/Core/ILambdaConfigurator.cs, src/Core/ILambdaStartup.cs, src/Core/LambdaHost.cs, src/Core/LambdaServiceCollectionExtensions.cs, src/Encryption/DefaultDecryptionService.cs, src/Encryption/EncryptionAttribute.cs, src/Encryption/IDecryptionService.cs
Adds documentation comments to public facing APIs.
=> LAMBJ-2 Documentation Comments

.github/releases/v0.3.0-beta2.md, README.md, examples/AwsClientFactories/README.md
Adds links to the two examples in the README.
=> LAMBJ-12 Link Examples in README

.github/releases/v0.3.0-beta2.md, .github/workflows/ci.yml, .vscode/tasks.json, CONTRIBUTING.md, Makefile, README.md, tests/WithFactories/ConfigurationIntegrationTests.cs, tests/WithFactories/Core/LambdaHostBuilderTests.cs, tests/WithFactories/Core/LambdaHostTests.cs, tests/WithFactories/Encryption/DefaultDecryptionServiceTests.cs, tests/WithFactories/IntegrationTests.cs, tests/WithoutFactories/IntegrationTests.cs
This adds test categories to all test fixtures and adds a contributing guide to the repository.  Disabled Github Issues in favor of JIRA (issues can be reported anonymously there).
=> LAMBJ-4 Test Categories & Contributing Guide

.editorconfig
Organizes and documents our editor config rules.
=> LAMBJ-3 Organize EditorConfig Rules

.github/releases/v0.3.0.md, .github/workflows/ci.yml, after.lambdajection.sln.targets, examples/Directory.Build.props, src/Generator/Generator.csproj, src/Generator/Generator.props
Automatically adds GenerateRuntimeConfigurationFiles=true to consuming projects.
=> LAMBJ-20 GenerateRuntimeConfigurationFiles Property

.github/releases/v0.3.0.md, .vscode/settings.json, README.md
Adds documentation around using development builds
=> LAMBJ-31 Development Build Documentation

README.md
Adds project goals to the README.
=> LAMBJ-27 Project Goals

.github/FUNDING.yml
Adds a FUNDING.yml file to the .github folder to enable our sponsor badge.
=> LAMBJ-39 Funding Information

README.md, SECURITY.md
This adds a security policy to the repository.
=> LAMBJ-33 Security Policy

.github/releases/v0.4.0-beta2.md, src/Core/Core.csproj, src/Core/packages.lock.json, src/Generator/packages.lock.json, tests/Integration/NoFactoryCompilationTestProject/packages.lock.json, tests/packages.lock.json
Bumped Amazon.Lambda.Serialization.SystemTextJson to v2.0.2
=> LAMBJ-68 Upgrade Serialization Library

.github/releases/v0.4.0-beta2.md, src/Encryption/Encryption.csproj
Now publishing Symbols + SourceLink information for Lambdajection.Encryption
=> LAMBJ-69 Encryption Package Symbols

.github/releases/v0.4.0.md, version.json
This prepares the repository for the next (v0.4.0) release by bumping the version and adding a release notes file.
=> LAMBJ-47 v0.4.0 Release Preparations

.github/releases/v0.5.0-beta1.md, version.json
Prepares the repository for the next release (v0.5.0-beta1)
- Bumped version in version.json
- Added release notes file
=> LAMBJ-72 v0.5.0-beta1 Release Preparations

.github/releases/v0.5.0-beta2.md, README.md, version.json
Makes preparations for the v0.5.0-beta2 release.
=> LAMBJ-85 v0.5.0-beta2 Release Preparations

.editorconfig, .github/releases/v0.5.0-beta2.md, after.lambdajection.sln.targets, src/Templates/Templates.csproj, templates/Options/.template.config/template.json, templates/Options/Options.cs, templates/Options/Options.csproj, templates/Project/.template.config/template.json, templates/Project/Handler.cs, templates/Project/Startup.cs, templates/templates.sln
Fixes an issue where several template symbols were being replaced where they should not be (ie Options being replaced in the LambdaOptions attribute if you specified a custom options class name).
=> LAMBJ-82 Fix Symbol Over-replacement

examples/AwsClientFactories/cloudformation.template.yml, examples/CustomConfiguration/CustomConfiguration.csproj, examples/CustomConfiguration/cloudformation.template.yml, examples/CustomSerializer/cloudformation.template.yml, examples/Directory.Build.targets, examples/EncryptedOptions/cloudformation.template.yml
This prefixes the example stacks when they are deployed for running end-to-end tests
=> LAMBJ-81 Example Stack Prefixes

README.md
Makes several adjustments to the README / Documentation that were outdated or needed new verbiage.
=> README / Documentation Updates

.github/releases/v0.5.0-beta3.md, version.json
Makes the necessary preparations for a v0.5.0-beta3 release:
- Bump version to v0.5.0-beta2 
- Add release notes file
=> LAMBJ-90 v0.5.0-beta3 Release Preparations

.github/workflows/ci.yml, examples/CustomConfiguration/CustomConfiguration.csproj
=> CICD Updates

.github/workflows/ci.yml
Set the CICD Schedule to run everyday at midnight.
=> CICD Updates Pt 2

.github/releases/v0.5.0.md, version.json
Prepares the repo for v0.5.0 release
=> LAMBJ-94 v0.5.0 Release Preparations

.github/releases/v0.5.0.md, Directory.Build.props, src/Attributes/packages.lock.json, src/Core/Core.csproj, src/Core/packages.lock.json, src/Encryption/Encryption.csproj, src/Encryption/packages.lock.json, src/Generator/Generator.csproj, src/Generator/packages.lock.json, src/Metapackage/packages.lock.json, src/Runtime/Runtime.csproj, src/Runtime/packages.lock.json, src/Templates/packages.lock.json, tests/Tests.csproj, tests/packages.lock.json
This updates any outdated dependencies as of 10/27
=> LAMBJ-93 Update Dependencies

.github/releases/v0.5.0.md, src/Core/Core.csproj, src/Core/packages.lock.json, src/Generator/packages.lock.json, src/Metapackage/packages.lock.json, tests/packages.lock.json
This updates Microsoft.Extensions.* dependencies to .NET 5 RC2
=> LAMBJ-93 Update Microsoft.Extensions.* to .NET 5 RC2

.github/releases/v0.5.0.md, Directory.Build.props, global.json, src/Attributes/packages.lock.json, src/Core/Core.csproj, src/Core/packages.lock.json, src/Encryption/Encryption.csproj, src/Encryption/packages.lock.json, src/Generator/Generator.csproj, src/Generator/packages.lock.json, src/Metapackage/packages.lock.json, src/Runtime/packages.lock.json, src/Templates/packages.lock.json, tests/Tests.csproj, tests/packages.lock.json
Upgrades the project to full .NET 5 along with other dependency upgrades.
=> Update to .NET 5 & Other Dependency Upgrades

examples/CustomRuntime/cloudformation.config.json
This upgrades the .NET 5 Lambda Layer to the full .NET 5 version.
=> Upgrade Runtime Lambda Layer to .NET 5

.github/releases/v0.5.0.md
Includes release notes updates for v0.5.0
=> Release Notes Updates for v0.5.0

.github/releases/v0.6.0-beta1.md, version.json
This makes release preparations for v0.6.0-beta1
=> LAMBJ-95 v0.6.0-beta1 Release Preparations

.github/releases/v0.6.0-beta1.md, templates/Project/.template.config/template.json, templates/Project/Handler.cs
This introduces a new project template option: disposable.  Set this to true if you want the generated lambda to implement IAsyncDisposable and IDisposable.
=> LAMBJ-79 Disposable Lambda Template

.github/releases/v0.6.0-beta1.md, examples/AwsClientFactories/Handler.cs, examples/AwsClientFactories/README.md, examples/CustomSerializer/EmbeddedResourceReader.cs, examples/CustomSerializer/Handler.cs, examples/CustomSerializer/README.md, examples/CustomSerializer/ResourceContext.cs
To help give a better idea how to use disposables, a couple examples have been updated to use both IDisposable and IAsyncDisposable.
=> LAMBJ-80 Implement IDisposable, IAsyncDisposable in Examples

.github/releases/v0.6.0-beta1.md, after.lambdajection.sln.targets, src/Generator/AwsFactoryGenerator.cs, src/Generator/ConfiguratorGenerator.cs, src/Generator/LambdaGenerator.cs, src/Generator/OptionsDecryptorGenerator.cs, src/Generator/UnitGenerator.cs, tests/Compilation/Utils/MSBuildProjectExtensions.cs
The generator has been refactored for better modularity.
=> LAMBJ-74 Generator Modularization

.github/releases/v0.6.0-beta1.md, Directory.Build.props, src/Attributes/packages.lock.json, src/Core/Core.csproj, src/Core/packages.lock.json, src/Encryption/Encryption.csproj, src/Encryption/packages.lock.json, src/Generator/Generator.csproj, src/Generator/packages.lock.json, src/Metapackage/packages.lock.json, src/Runtime/packages.lock.json, src/Templates/packages.lock.json, tests/Tests.csproj, tests/packages.lock.json
- Updated Microsoft.CodeAnalysis.* Dependencies from 3.8.0-5.final to 3.8.0
- Updated AWSSDK.Core from 3.5.1.34 to 3.5.1.42
- Updated AWSSDK.KeyManagementService from 3.5.0.36 to 3.5.0.42
=> LAMBJ-96 Update Outdated Dependencies

examples/AwsClientFactories/cloudformation.config.json, examples/CustomConfiguration/cloudformation.config.json, examples/CustomRuntime/cloudformation.config.json, examples/CustomSerializer/cloudformation.config.json, examples/EncryptedOptions/cloudformation.config.json
This adds tags to the example stacks.
=> LAMBJ-84 Example Stack Tags

.github/releases/v0.6.0-beta2.md, README.md, examples/CustomRuntime/CustomRuntime.csproj, src/Attributes/LambdaAttribute.cs, src/Generator/GenerationContext.cs, src/Generator/LambdaGenerator.cs, src/Generator/UnitGenerator.cs, tests/Compilation/Projects/CustomRunnerMethod/CustomRunnerMethod.csproj, tests/Compilation/Projects/CustomRunnerMethod/Handler.cs, tests/Compilation/Projects/CustomRunnerMethod/Startup.cs, tests/Compilation/Projects/compilation-projects.sln, tests/Compilation/Tests/CustomRunnerMethodTests.cs, tests/Tests.csproj, tests/packages.lock.json
The "Run" method name can now be customized using the RunnerMethod property in the Lambda Attribute.
=> LAMBJ-83 Runner Method Configuration

.github/releases/v0.6.0-beta4.md, version.json
This makes preparations for the v0.6.0-beta4 release
=> v0.6.0-beta4 Release Preparations

.github/releases/v0.6.0.md, examples/Directory.Build.props, src/Layer/Layer.csproj, src/Layer/packages.lock.json, version.json
This prepares the project for v0.6.0 release:
- Bumps version in version.json
- Adds release notes file
- Upgrades Cythral.CloudFormation.BuildTasks to v0.4.1
=> v0.6.0 Release Preparations

.github/releases/v0.6.0.md, README.md
This updates the release notes for v0.6.0 and the README in preparation for the release today.
=> Update Release Notes and README

src/CustomResource/CustomResourceResponseStatus.cs, src/CustomResource/CustomResourceResponseStatusConverter.cs, tests/Compilation/Tests/CustomResourcesTests.cs, tests/Compilation/Tests/Setup.cs, tests/Setup.cs, tests/Unit/CustomResource/CustomResourceResponseStatusConverterTests.cs
Serializes custom resource response statuses to all caps strings
=> LAMBJ-108 Response Status Serialization

.github/releases/v0.7.0-beta2.md, version.json
This makes release preparations for v0.7.0-beta2
=> v0.7.0-beta2 Release Preparations

examples/AwsClientFactories/AwsClientFactories.csproj, examples/CustomConfiguration/CustomConfiguration.csproj, examples/CustomRuntime/CustomRuntime.csproj, examples/CustomSerializer/CustomSerializer.csproj, examples/EncryptedOptions/EncryptedOptions.csproj
While creating the last e2e test, I turned off the others to make the test process go faster. This turns them all back on.
=> Turn on all E2E Tests

.github/releases/v0.7.0-beta2.md
Updates release notes with the most recent changes to dependencies and dependency management.
=> Updates for Release Notes

.github/workflows/dependency-updates.yml
This updates the email and name of the account used by nukeeper to open PRs.
=> Nukeeper Account Update

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependency-updates.yml
This adds CICD Notifications for Discord.
=> LAMBJ-100 Discord Notifications

.github/auto_assign.yml, .github/workflows/assign-prs.yml
This automatically assigns PRs to me when they are opened, reopened or marked as ready for review.
=> Auto Assign PRs

.github/releases/v0.7.0-beta3.md, version.json
Release preparations for v0.7.0-beta3:
- Bumped version in version.json
- Added release notes
=> v0.7.0-beta3 Release Preparations

examples/CustomResource/CustomResource.csproj, examples/CustomResource/README.md, examples/CustomResource/Request.cs, examples/CustomResource/cloudformation.template.yml
Adds documentation to the custom resource example.
=> LAMBJ-110 Custom Resource Example Documentation

version.json
Release prep for v0.7.0:
- Added release notes file
- Bumped version in version.json
=> v0.7.0 Release Prep

version.json
This prepares the the repo for v0.8.0-beta1 release.
=> v0.8.0-beta1 Release Prep

examples/CustomSerializer/Resources/about.html, examples/CustomSerializer/cloudformation.template.yml, examples/Directory.Build.targets
Now using the cfn-build-tasks task for retrieving a get output value task.
=> LAMBJ-122 Get Stack Output Task

.github/releases/v0.8.0-beta4.md, src/Generator/Program.cs, src/Generator/ProgramHost.cs
- Fixed an issue where compilation would sometimes fail for custom resources with an error like 'Could not load file Microsoft.Extensions.Hosting'.
=> Assembly Loading Hotfix

.github/releases/v0.9.0-beta3.md, src/Sns/Models/CloudFormationStackEvent.cs, src/Sns/Serialization/CloudFormationStackEventConverter.cs, tests/Unit/Sns/Serialization/CloudFormationStackEventConverterTests.cs
Adding a model + converter for CloudFormation Stack Notification in the Lambdajection.Sns package for processing stack notification events.
=> LAMBJ-141 Stack Notification Event Model + Converter

.github/releases/v0.9.0-beta4.md, src/Core/Serialization/StringConverter.cs, src/Sns/Serialization/CloudFormationStackEventConverter.cs, tests/Compilation/Projects/Sns/Handler.cs, tests/Compilation/Projects/Sns/Request.cs, tests/Compilation/Tests/SnsTests.cs, tests/Tests.csproj, tests/Unit/Sns/Serialization/CloudFormationStackEventConverterTests.cs
Fixes an issue where SnsMessage objects would fail to deserialize.
=> LAMBJ-144 SnsMessage Deserialization Issue

.github/workflows/ci.yml, after.lambdajection.sln.targets, examples/AwsClientFactories/cloudformation.template.yml, examples/CustomConfiguration/cloudformation.template.yml, examples/CustomResource/cloudformation.template.yml, examples/CustomRuntime/cloudformation.template.yml, examples/Directory.Build.props, examples/EncryptedOptions/cloudformation.template.yml, examples/SnsHandler/Handler.cs, examples/SnsHandler/Response.cs, examples/SnsHandler/SnsHandler.csproj, examples/SnsHandler/Startup.cs, examples/SnsHandler/cloudformation.config.json, examples/SnsHandler/cloudformation.template.yml, examples/examples.sln
Adds an end-to-end test for SNS Event Handler functionality
=> LAMBJ-137 SNS Handler End-to-End Test
