- .config/dotnet-tools.json
- .github/releases/v0.2.0.md
- Directory.Build.props
- global.json
- src/Attributes/packages.lock.json
- src/Core/packages.lock.json
- src/Directory.Build.props
- src/Generator/packages.lock.json
- src/Metapackage/packages.lock.json
- tests/packages.lock.json
- Bumped Cythral.CodeGeneration.Roslyn to v0.9.0 to get rid of build warnings around using prerelease versions
- Bumped GitVersioning to v3.2.31 to get builds working on unsupported linux distros (mainly ArchLinux haha)
- Consolidated Directory.Build.props files - since GitVersioning works on linux now, don't need to restrict this to just the projects in the src folder.
> CYTHINF-139 Bump CGR & GitVersioning

- .github/releases/v0.2.1.md
- src/Generator/LambdaGenerator.cs
Now using Roslyn Diagnostics to report errors instead of throwing an exception.  The latter would lead to cryptic error messages.
> CYTHINF-148 Error Diagnostics

- tests/WithFactories/Core/LambdaHostBuilderTests.cs
- tests/WithFactories/Core/LambdaHostTests.cs
Cleaning up tests by aliasing the long generic names for LambdaHost<> and LambdaHostBuilder<>
> LAMBJ-5 LambdaHost and LambdaHostBuilder Aliases

- .github/releases/v0.3.0-beta2.md
- README.md
- examples/AwsClientFactories/Startup.cs
- examples/AwsClientFactories/cloudformation.template.yml
- examples/Directory.Build.props
- examples/EncryptedOptions/Startup.cs
- examples/EncryptedOptions/cloudformation.template.yml
- src/Core/ILambdaStartup.cs
- src/Core/LambdaHost.cs
- src/Core/LambdaHostBuilder.cs
- src/ExamplesTool/ExamplesTool.csproj
- tests/WithFactories/ConfigurationIntegrationTests.cs
- tests/WithFactories/Core/LambdaHostBuilderTests.cs
- tests/WithFactories/IntegrationTests.cs
- tests/WithoutFactories/IntegrationTests.cs
Introduces 2 new breaking changes. 
- Startup classes are now added to the service collection and use constructor DI to inject the IConfiguration object (this matches the approach that ASP.NET Core uses). The Configuration property on ILambdaStartup has been removed and is no longer set during lambda startup.
- The LambdaHost constructor allowing a custom builder function/action has been marked as internal, as this was only intended for internal testing purposes.
> LAMBJ-25 Startup Constructor DI

- .github/releases/v0.3.0-beta3.md
- src/Generator/LambdaGenerator.cs
- tests/WithFactories/IntegrationTests.cs
Fixes an issue where client factories would attempt to do an sts:AssumeRole if no role arn was given.
> LAMBJ-36 Client Factories RoleArn Fix

- .github/releases/v0.3.0-beta3.md
- src/Generator/LambdaGenerator.cs
- tests/WithFactories/IntegrationTests.cs
- version.json
This release introduces the following:
- Fixes an issue where client factories would attempt to do an sts:AssumeRole if no role arn was given.
<h2>        Stories
</h2>
<ul>
<li>[<a href='https://cythral.atlassian.net/browse/LAMBJ-36'>LAMBJ-36</a>] -         AWS Factories Invalid RoleArn Condition
</li>
</ul>
> LAMBJ-37 v0.3.0-beta3

- .github/releases/v0.3.0.md
- src/Core/LambdaHostBuilder.cs
Lambda service providers are now initialized at their declaration, rather than inside the LambdaHostBuilder.Build method. This leads to faster (albeit slight) startup times due to the fact that the field does not get initialized to null once then be reassigned later during runtime.
> LAMBJ-29 Static Service Provider Initialization

- .github/releases/v0.4.0-beta1.md
- Makefile
- README.md
- examples/AwsClientFactories/AwsClientFactories.csproj
- examples/AwsClientFactories/Handler.cs
- examples/EncryptedOptions/EncryptedOptions.csproj
- examples/EncryptedOptions/Handler.cs
- src/Attributes/LambdaAttribute.cs
- src/Core/Core.csproj
- src/Core/packages.lock.json
- src/Generator/LambdaGenerator.cs
- src/Generator/packages.lock.json
- tests/Integration/NoFactoryCompilationTestProject/packages.lock.json
- tests/Integration/SerializerIntegrationTests.cs
- tests/packages.lock.json
You can now control the serializer used on the Lambda by setting the Serializer argument in the Lambda attribute.  If your Lambda targets netcoreapp3.1, then DefaultLambdaJsonSerializer from Amazon.Lambda.Serialization.SystemTextJson is used by default.
> LAMBJ-13 Serialization

- .github/releases/v0.4.0-beta1.md
- README.md
- examples/AwsClientFactories/Handler.cs
- examples/EncryptedOptions/Handler.cs
- src/Attributes/LambdaAttribute.cs
- src/Core/Properties.cs
- src/Generator/LambdaGenerator.cs
- tests/Integration/AwsDependencyIntegrationTests.cs
- tests/Integration/ConfigurationIntegrationTests.cs
- tests/Integration/NoFactoryCompilationTestProject/IntegrationTests.cs
- tests/Integration/SerializerIntegrationTests.cs
The startup argument in the Lambda attribute is now a constructor argument, rather than a named one.  This was done to enforce setting the argument earlier in the pipeline, rather than just failing during code generation.
> LAMBJ-11 Startup Constructor Argument

- .github/releases/v0.4.0-beta2.md
- .github/workflows/ci.yml
- after.lambdajection.sln.targets
- src/Core/LambdaHost.cs
- src/Core/LambdaHostBuilder.cs
- src/Generator/LambdaGenerator.cs
- tests/Unit/Core/LambdaHostBuilderTests.cs
- tests/Unit/Core/LambdaHostTests.cs
- Updates decryption to use initialization services for the following benefits:
- Avoid possibility of deadlocks by not using Task.WaitAll in the post configure hook.
- Run decryption on multiple IOptions in parallel
- Run decryption in parallel with other initialization services.
- Fixes an issue where initialization services were getting called on every call to the Lambda.
- Now checking for correct formatting across the solution after every build, including in CICD.  This means PR checks will fail if your changes to not comply with our preferred code style.
> LAMBJ-44 Decryption Initialization Service

- .github/releases/v0.4.0-beta2.md
- src/Attributes/Attributes.csproj
Lambdajection.Attributes has been converted to a reference assembly so that it (and its dependencies) are not copied to the output folder of your project.  This package has always only contained symbols that are compile-time only, so this will simply free up space in deployment packages.
> LAMBJ-28 Attributes Reference Assembly

- .github/releases/v0.4.0-beta2.md
- after.lambdajection.sln.targets
- src/Attributes/Attributes.csproj
- src/Core/Core.csproj
- src/Core/LambdaHost.cs
- src/Core/LambdaHostBuilder.cs
- src/Core/packages.lock.json
- src/Encryption/Encryption.csproj
- src/Generator/LambdaGenerator.cs
- src/Generator/packages.lock.json
- tests/Integration/NoFactoryCompilationTestProject/packages.lock.json
- tests/Unit/Core/LambdaHostBuilderTests.cs
- tests/Unit/Core/LambdaHostTests.cs
- tests/packages.lock.json
- version.json
This release introduces the following:
- Updates decryption to use initialization services for the following benefits:
- Avoid possibility of deadlocks by not using Task.WaitAll in the post configure hook.
- Run decryption on multiple IOptions in parallel
- Run decryption in parallel with other initialization services.
- Fixes an issue where initialization services were getting called on every call to the Lambda.
- Now checking for correct formatting across the solution after every build, including in CICD.  This means PR checks will fail if your changes to not comply with our preferred code style.
- Lambdajection.Attributes has been converted to a reference assembly so that it (and its dependencies) are not copied to the output folder of your project.  This package has always only …
> LAMBJ-66 v0.4.0-beta2

- .github/releases/v0.5.0-beta1.md
- Directory.Packages.props
- global.json
- src/Attributes/packages.lock.json
- src/Core/packages.lock.json
- src/Generator/LambdaCompilationScanner.cs
- src/Generator/LambdaGenerator.cs
- src/Generator/packages.lock.json
- src/Metapackage/packages.lock.json
- tests/Integration/NoFactoryCompilationTestProject/packages.lock.json
- tests/packages.lock.json
Upgrades Roslyn to 3.7.0 for latest bug and security fixes, along with increased nullability checks.  Addressed changes around new possible null references.
> LAMBJ-71 Update Roslyn

- README.md
- templates/Options/.template.config/template.json
This fixes the options template name to better identify its template.  This was a copy-paste error.
> LAMBJ-16 Options Template Name

- .github/releases/v0.5.0-beta1.md
- README.md
- src/Core/LambdaHost.cs
- src/Generator/LambdaGenerator.cs
- tests/Common/AsyncDisposableLambda.cs
- tests/Common/DisposableLambda.cs
- tests/Common/MultiDisposableLambda.cs
- tests/Integration/DisposableIntegrationTests.cs
- tests/Unit/Core/LambdaHostBuilderTests.cs
- tests/Unit/Core/LambdaHostTests.cs
IDisposable and IAsyncDisposable Lambdas are now fully supported.  Disposers will be called at the end of each invocation. If you implement both IDisposable and IAsyncDisposable, DisposeAsync will be preferred.
> LAMBJ-26 Disposable Lambdas

- .github/releases/v0.5.0-beta2.md
- src/Generator/LambdaGenerator.cs
- tests/Integration/AwsDependencyIntegrationTests.cs
Fixes an issue where an IAwsFactory was not being generated and added to the service collection for IAmazonSecurityTokenService.  This was not happening for any other service.
> LAMBJ-86 Generate Security Token Service Factory

- .github/releases/v0.5.0-beta2.md
- src/Core/LambdaHost.cs
- tests/Unit/Core/LambdaHostTests.cs
Initialization services that implement IAsyncDisposabe or IDisposable will now be properly disposed prior to running your Lambda's handler.
> LAMBJ-78 Disposable Initialization Services

- Directory.Build.props
- src/Metapackage/build/Lambdajection.targets
- Uses the MSBuild::VersionLessThan function for comparing version strings rather than numerical comparison. 
- Sets MinClientVersion to 2.5
> Build Settings Updates

- .editorconfig
- .github/releases/v0.5.0-beta3.md
- src/Core/Core.csproj
- src/Core/Properties.cs
- src/Generator/GenerationContext.cs
- src/Generator/GenerationSettings.cs
- src/Generator/Generator.csproj
- src/Generator/LambdaGenerator.cs
- src/Generator/UsingsGenerator.cs
- tests/Common/AutoAttribute.cs
- tests/Common/TargetAttribute.cs
- tests/Common/TargetRelay.cs
- tests/Integration/ConfigurationIntegrationTests.cs
- tests/Tests.csproj
- tests/Unit/Generator/UsingsGeneratorTests.cs
- tests/packages.lock.json
This fixes an issue where adding a static using in a source document would result in a compilation failure, due to the generator translating this into a normal using statement.
> LAMBJ-89 Allow Static Usings

- tests/Tests.csproj
Fixes an issue where running dotnet test without the --no-build flag would result in a compilation error.
> Test Command Fix

- .github/releases/v0.6.0-beta1.md
- examples/AwsClientFactories/AwsClientFactories.csproj
- examples/AwsClientFactories/cloudformation.template.yml
- examples/Directory.Build.props
- examples/Directory.Build.targets
As a housekeeping item, CloudFormation stacks for examples are now deleted after end to end tests have finished running.
> LAMBJ-97 Example Stack Cleanup

- .github/releases/v0.6.0-beta1.md
- examples/AwsClientFactories/Handler.cs
- examples/CustomConfiguration/Handler.cs
- examples/CustomRuntime/Handler.cs
- examples/CustomSerializer/Handler.cs
- examples/EncryptedOptions/Handler.cs
- src/Core/ILambda.cs
- src/Core/LambdaHost.cs
- src/Core/LambdaHostBuilder.cs
- src/Core/LambdaScope.cs
- src/Generator/LambdaGenerator.cs
- templates/Project/Handler.cs
- tests/Common/TestLambda.cs
- tests/Compilation/Projects/ConfigFactory/Handler.cs
- tests/Compilation/Projects/Configuration/Handler.cs
- tests/Compilation/Projects/Disposables/AsyncDisposableHandler.cs
- tests/Compilation/Projects/Disposables/DisposableHandler.cs
- tests/Compilation/Projects/LambdaContext/Handler.cs
- tests/Compilation/Projects/LambdaContext/LambdaContext.csproj
- tests/Compilation/Projects/LambdaContext/Startup.cs
- tests/Compilation/Projects/Serializer/CustomSerializerHandler.cs
- tests/Compilation/Projects/Serializer/DefaultSerializerHandler.cs
- tests/Compilation/Projects/compilation-projects.sln
- tests/Compilation/Tests/LambdaContextTests.cs
- tests/Unit/Core/LambdaHostTests.cs
The context parameter (ILambdaContext) has been removed from ILambda.Handle.  This can now (optionally) be accessed via a constructor argument instead.  This was done to simplify the composition process and reduce the number of arguments that Handle will have - we plan on introducing cancellation tokens in the future here instead.
> LAMBJ-87 Context Constructor Argument

- .github/releases/v0.6.0-beta3.md
- src/Layer/Layer.csproj
- src/Layer/Layer.template.yml
- src/Layer/THIRD-PARTY-NOTICES.txt
- version.json
I noticed v0.6.0-beta2 would not be publishable since the Lambda Layer did not include our kind dependencies' license information nor our own.  Also added an output for the Lambda Layer's ARN.
> v0.6.0-beta3: Layer Patches

- .github/workflows/ci.yml
When the ci/cd workflow was updated to publish the layer to SAR, the nuget download id was changed to download-nugets but not updated in the github release step.  This fixes the github release step to use the correct download id.
> CD Github Release: Fix Uploading Nugets

- .github/releases/v0.6.0-beta4.md
- examples/AwsClientFactories/Handler.cs
- examples/CustomConfiguration/Handler.cs
- examples/CustomRuntime/Handler.cs
- examples/CustomSerializer/Handler.cs
- examples/EncryptedOptions/Handler.cs
- src/Core/ILambda.cs
- src/Core/ILambdaInitializationService.cs
- src/Core/LambdaHost.cs
- src/Encryption/DefaultDecryptionService.cs
- src/Encryption/IDecryptionService.cs
- src/Generator/LambdaCompilationScanner.cs
- src/Generator/OptionsDecryptorGenerator.cs
- src/Generator/UnitGenerator.cs
- src/Generator/UsingsGenerator.cs
- templates/Project/Handler.cs
- tests/Common/TestLambda.cs
- tests/Compilation/Projects/AmazonFactories/Handler.cs
- tests/Compilation/Projects/ConfigFactory/Handler.cs
- tests/Compilation/Projects/Configuration/Handler.cs
- tests/Compilation/Projects/CustomRunnerMethod/Handler.cs
- tests/Compilation/Projects/Disposables/AsyncDisposableHandler.cs
- tests/Compilation/Projects/Disposables/DisposableHandler.cs
- tests/Compilation/Projects/LambdaContext/Handler.cs
- tests/Compilation/Projects/Serializer/CustomSerializerHandler.cs
- tests/Compilation/Projects/Serializer/DefaultSerializerHandler.cs
**Breaking Change**: Lambdas now take a CancellationToken as a second argument and will gracefully stop execution when cancellation is requested.
> LAMBJ-19 Task Cancellation

- .github/releases/v0.6.0-beta4.md
- tests/Common/TargetRelay.cs
- tests/Unit/Core/LambdaConfigFactoryTests.cs
- tests/Unit/Core/LambdaHostBuilderTests.cs
- tests/Unit/Core/LambdaHostTests.cs
- tests/Unit/Encryption/DefaultDecryptionServiceTests.cs
This converts unit tests to use autofixture where applicable to conform to best practices regarding generation of test data and setup.
> LAMBJ-77 Use AutoFixture in Unit Tests

- README.md
- version.json
This updates the README docs with a link to the Lambdajection Layer on SAR along with usage instructions. Additionally, this bumps the version to v0.7.0-beta1 and adds an associated release notes file.
> LAMBJ-101 SAR Link + Layer Docs

- examples/CustomSerializer/CustomSerializer.csproj
NuKeeper has generated a minor update of `Amazon.Lambda.ApplicationLoadBalancerEvents` to `2.1.0` from `2.0.0`
`Amazon.Lambda.ApplicationLoadBalancerEvents 2.1.0` was published at `2020-10-21T23:12:51Z`, 4 months ago
Updated `examples/CustomSerializer/CustomSerializer.csproj` to `Amazon.Lambda.ApplicationLoadBalancerEvents` `2.1.0` from `2.0.0`
[Amazon.Lambda.ApplicationLoadBalancerEvents 2.1.0 on NuGet.org](https://www.nuget.org/packages/Amazon.Lambda.ApplicationLoadBalancerEvents/2.1.0)
> Automatic update of Amazon.Lambda.ApplicationLoadBalancerEvents to 2.1.0

- tests/Tests.csproj
- tests/packages.lock.json
NuKeeper has generated a major update of `coverlet.collector` to `3.0.2` from `1.3.0`
`coverlet.collector 3.0.2` was published at `2021-01-24T13:16:46Z`, 9 days ago
Updated `tests/Tests.csproj` to `coverlet.collector` `3.0.2` from `1.3.0`
[coverlet.collector 3.0.2 on NuGet.org](https://www.nuget.org/packages/coverlet.collector/3.0.2)
> Automatic update of coverlet.collector to 3.0.2

- examples/CustomConfiguration/CustomConfiguration.csproj
- tests/Compilation/Projects/ConfigFactory/ConfigFactory.csproj
NuKeeper has generated a major update of `Microsoft.Extensions.Configuration.Json` to `5.0.0` from `3.1.8`
`Microsoft.Extensions.Configuration.Json 5.0.0` was published at `2020-11-09T23:40:12Z`, 3 months ago
2 project updates:
Updated `examples/CustomConfiguration/CustomConfiguration.csproj` to `Microsoft.Extensions.Configuration.Json` `5.0.0` from `3.1.8`
Updated `tests/Compilation/Projects/ConfigFactory/ConfigFactory.csproj` to `Microsoft.Extensions.Configuration.Json` `5.0.0` from `3.1.8`
[Microsoft.Extensions.Configuration.Json 5.0.0 on NuGet.org](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/5.0.0)
> Automatic update of Microsoft.Extensions.Configuration.Json to 5.0.0

- tests/Tests.csproj
- tests/packages.lock.json
NuKeeper has generated a  update of `NuGet.ProjectModel` to `5.9.0-rc.7046` from `5.9.0-preview.2`
`NuGet.ProjectModel 5.9.0-rc.7046` was published at `2021-01-22T02:39:02Z`, 11 days ago
Updated `tests/Tests.csproj` to `NuGet.ProjectModel` `5.9.0-rc.7046` from `5.9.0-preview.2`
> Automatic update of NuGet.ProjectModel to 5.9.0-rc.7046

- tests/Tests.csproj
- tests/packages.lock.json
NuKeeper has generated a minor update of `Microsoft.Build.Locator` to `1.4.1` from `1.3.2`
`Microsoft.Build.Locator 1.4.1` was published at `2021-01-21T20:09:11Z`, 11 days ago
Updated `tests/Tests.csproj` to `Microsoft.Build.Locator` `1.4.1` from `1.3.2`
[Microsoft.Build.Locator 1.4.1 on NuGet.org](https://www.nuget.org/packages/Microsoft.Build.Locator/1.4.1)
> Automatic update of Microsoft.Build.Locator to 1.4.1

- tests/Tests.csproj
- tests/packages.lock.json
NuKeeper has generated a  update of `AWSSDK.SecurityToken` to `3.5.1.45` from `3.5.1.37`
`AWSSDK.SecurityToken 3.5.1.45` was published at `2021-01-29T20:56:37Z`, 4 days ago
Updated `tests/Tests.csproj` to `AWSSDK.SecurityToken` `3.5.1.45` from `3.5.1.37`
[AWSSDK.SecurityToken 3.5.1.45 on NuGet.org](https://www.nuget.org/packages/AWSSDK.SecurityToken/3.5.1.45)
> Automatic update of AWSSDK.SecurityToken to 3.5.1.45

- tests/Tests.csproj
- tests/packages.lock.json
NuKeeper has generated a minor update of `NUnit` to `3.13.1` from `3.12.0`
`NUnit 3.13.1` was published at `2021-02-01T01:29:59Z`, 1 day ago
Updated `tests/Tests.csproj` to `NUnit` `3.13.1` from `3.12.0`
[NUnit 3.13.1 on NuGet.org](https://www.nuget.org/packages/NUnit/3.13.1)
> Automatic update of NUnit to 3.13.1

- tests/Tests.csproj
- tests/packages.lock.json
NuKeeper has generated a  update of `AWSSDK.S3` to `3.5.7.12` from `3.5.7.4`
`AWSSDK.S3 3.5.7.12` was published at `2021-01-29T20:56:16Z`, 4 days ago
Updated `tests/Tests.csproj` to `AWSSDK.S3` `3.5.7.12` from `3.5.7.4`
[AWSSDK.S3 3.5.7.12 on NuGet.org](https://www.nuget.org/packages/AWSSDK.S3/3.5.7.12)
> Automatic update of AWSSDK.S3 to 3.5.7.12

- src/Core/Core.csproj
- src/Core/packages.lock.json
- src/Generator/Generator.csproj
- src/Generator/packages.lock.json
- src/Metapackage/packages.lock.json
- tests/packages.lock.json
NuKeeper has generated a patch update of `AWSSDK.Core` to `3.5.2.5` from `3.5.1.57`
`AWSSDK.Core 3.5.2.5` was published at `2021-01-30T02:27:39Z`, 3 days ago
2 project updates:
Updated `src/Generator/Generator.csproj` to `AWSSDK.Core` `3.5.2.5` from `3.5.1.57`
Updated `src/Core/Core.csproj` to `AWSSDK.Core` `3.5.2.5` from `3.5.1.57`
[AWSSDK.Core 3.5.2.5 on NuGet.org](https://www.nuget.org/packages/AWSSDK.Core/3.5.2.5)
> Automatic update of AWSSDK.Core to 3.5.2.5

- tests/Tests.csproj
- tests/packages.lock.json
NuKeeper has generated a patch update of `AWSSDK.S3` to `3.5.8` from `3.5.7.12`
`AWSSDK.S3 3.5.8` was published at `2021-02-02T23:22:11Z`, 16 hours ago
Updated `tests/Tests.csproj` to `AWSSDK.S3` `3.5.8` from `3.5.7.12`
[AWSSDK.S3 3.5.8 on NuGet.org](https://www.nuget.org/packages/AWSSDK.S3/3.5.8)
> Automatic update of AWSSDK.S3 to 3.5.8

- tests/Tests.csproj
- tests/packages.lock.json
NuKeeper has generated a  update of `NuGet.ProjectModel` to `5.9.0-rc.7097` from `5.9.0-rc.7046`
`NuGet.ProjectModel 5.9.0-rc.7097` was published at `2021-02-02T23:57:54Z`, 15 hours ago
Updated `tests/Tests.csproj` to `NuGet.ProjectModel` `5.9.0-rc.7097` from `5.9.0-rc.7046`
> Automatic update of NuGet.ProjectModel to 5.9.0-rc.7097

- src/Encryption/Encryption.csproj
- src/Encryption/packages.lock.json
- src/Generator/packages.lock.json
- src/Layer/Manifest/Manifest.csproj
- src/Metapackage/packages.lock.json
- tests/packages.lock.json
NuKeeper has generated a patch update of `AWSSDK.KeyManagementService` to `3.5.2.6` from `3.5.1.6`
`AWSSDK.KeyManagementService 3.5.2.6` was published at `2021-01-29T20:54:11Z`, 4 days ago
Updated `src/Encryption/Encryption.csproj` to `AWSSDK.KeyManagementService` `3.5.2.6` from `3.5.1.6`
[AWSSDK.KeyManagementService 3.5.2.6 on NuGet.org](https://www.nuget.org/packages/AWSSDK.KeyManagementService/3.5.2.6)
> Automatic update of AWSSDK.KeyManagementService to 3.5.2.6

- src/Layer/Layer.csproj
- src/Layer/Manifest/Manifest.csproj
- src/Layer/packages.lock.json
This fixes it so that the AWSSDK.Core version is automatically detected for the Layer artifacts.xml
> LAMBJ-115 Automatically Determine AWSSDK.Core Version for Layer

- .github/releases/v0.7.0-beta2.md
- src/Generator/Generator.csproj
- src/Generator/packages.lock.json
- src/Layer/Layer.csproj
- src/Metapackage/packages.lock.json
- tests/packages.lock.json
This simplifies the Generator's dependency tree.  AWSSDK.Core is no longer a direct dependency, but may be loaded during runtime if needed.
> Dependency Simplifications

- .github/workflows/codeql-analysis.yml
This removes an unused CodeQL step (checking out HEAD^2) - we are no longer running CodeQL on pull requests so this step can be removed.
> LAMBJ-113 Remove Unused CodeQL Step

- .github/releases/v0.7.0-beta2.md
- src/Core/DefaultHttpClient.cs
- tests/Compilation/Tests/CustomResourcesTests.cs
Fixes an issue where error messages were being suppressed by a different message ('Invalid PhysicalResourceId') after responding to CloudFormation.
> LAMBJ-118 Dont Write Null PhysicalResourceIds

- examples/Directory.Build.targets
AWS CLI v2 is expecting Base64 Input by default, this sets the format to accept raw/plaintext lambda payloads.
> Fix E2E Tests

- .github/releases/v0.7.0-beta3.md
- src/Generator/ValidationsGenerator.cs
- tests/Compilation/Projects/CustomResources/ResourceProperties.cs
This fixes glaring issues with v0.7.0-beta2 that warrant an immediate release of beta3:
- Validations were being generated for private and protected properties
- The validation generator was recursing into collection types, causing a stack overflow
> v0.7.0-beta2 Hotfixes

- .github/releases/v0.8.3.md
- src/Generator/TemplateGeneration/Converters/GetAttTagConverter.cs
- src/Generator/TemplateGeneration/Converters/SubTagConverter.cs
- src/Generator/TemplateGeneration/Models/Role.cs
- src/Generator/TemplateGeneration/TemplateGenerator.cs
- tests/Compilation/Projects/Permissionless/Handler.cs
- tests/Compilation/Projects/Permissionless/Permissionless.csproj
- tests/Compilation/Projects/Permissionless/Startup.cs
- tests/Compilation/Projects/compilation-projects.sln
- tests/Compilation/Tests/PermissionlessTests.cs
- Fixes an issue where templates generated for Lambdas that don't interact with an AWS API would have a role policy with 0 actions, which is not allowed in CloudFormation.
> LAMBJ-131 Empty Policies

- .github/releases/v0.8.3.md
- src/CustomResource/CustomResourceRequest.cs
- src/Framework/NotValidatedAttribute.cs
- src/Generator/ValidationsGenerator.cs
- tests/Compilation/Tests/CustomResourcesTests.cs
Fixes an issue where validations were being applied to old resource properties, which would cause resource creation failures if using the validation attributes.
> LAMBJ-129 Don't Apply Validations to Old Resource Properties

- .github/releases/v0.9.0-beta4.md
- src/CustomResource/CustomResourceLambdaHost.cs
- src/CustomResource/CustomResourceRequest.cs
- tests/Unit/CustomResource/CustomResourceLambdaHostTests.cs
- ResponseURL is now an optional argument to custom resource requests, to allow for easier testing.  
- The lambda output for Custom Resources is now the full response that would've been sent to CloudFormation, rather than just the output data
> Nullable Custom Resource ResponseURL

- src/Core/Serialization/StringConverter.cs
- src/Sns/Models/CloudFormationStackEvent.cs
- src/Sns/Serialization/CloudFormationStackEventConverter.cs
- tests/Unit/Sns/Serialization/CloudFormationStackEventConverterTests.cs
Removes the Source Topic Property as this was mistakenly carried over from
an internal Cythral project.
Also fixes serialization of strings so that unicode quotes are not wrapped around the real value.
This was specifically happening for CloudFormationStackEvents.
> LAMBJ-148 Remove Source Topic Property

- src/Sns/SnsLambdaHost.cs
- tests/Compilation/Tests/SnsTests.cs
- tests/Unit/Sns/SnsLambdaHostTests.cs
Removes SNS Batching - these events will always only have 1 record so there is no need to loop through them.
> LAMBJ-149 Remove SNS Batching

- .github/workflows/ci.yml
- src/Generator/Generator.csproj
- src/Generator/Program.cs
- src/Generator/packages.lock.json
- src/Metapackage/packages.lock.json
- tests/packages.lock.json
Whenever an assembly was loaded into the generator, the version was not being checked.  So if there were multiple versions of the same assembly, there was a chance the version was wrong (and would later cause typeloadexceptions when attempting to load types from that assembly).
> Load Assemblies Into Generator AppDomain Only If Version Matches

- .github/releases/v0.9.2.md
- .vscode/settings.json
- src/CustomResource/CustomResourceRequest.cs
- src/CustomResource/CustomResourceResponse.cs
- version.json
Fixes an issue where custom resources would sometimes return an invalid physical resource id error.
> LAMBJ-150 Invalid PhysicalResourceId Error

- .github/releases/v0.10.0-beta1.md
- src/Layer/Layer.csproj
- src/Layer/Layer.template.yml
- src/Layer/Manifest/Manifest.csproj
The Lambdajection Lambda Layer now supports arm64-based lambdas.
> LAMBJ-151 ARM Layer
